logging.level:
  root: INFO
  pe.realplaza.security: DEBUG
  org.springframework.web: INFO
  org.apache.http: DEBUG

server:
  port: 8089
    
spring.jackson.time-zone: America/Lima
spring.jackson.locale: es_PE

spring:
  datasource:
    platform: sqlserver
    url: jdbc:sqlserver://localhost;databaseName=PRUEBA
    username: sa
    password: Theo@ndre
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: false
